name: Build WinForms App

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    
    - name: Restore NuGet packages
      run: nuget restore WindowsFormsApp1.sln
    
    - name: Build
      run: msbuild WindowsFormsApp1.sln /p:Configuration=Release /p:Platform="Any CPU"
    
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Build-Output
        path: bin/Release/
